#Pod’s configuration file specifies a PersistentVolumeClaim,
#but it does not specify a PersistentVolume.
#From the Pod’s point of view, the claim is a volume.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    k8s-app: mongo
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      k8s-app: mongo
  template:
    metadata:
      labels:
        k8s-app: mongo
    spec:
      nodeName: raspberrypi1
      containers:
      - image: mongo:bionic
        imagePullPolicy: Always
        name: mongo
        resources:
            limits:
                memory: "1Gi"
                cpu: "1"
            requests:
                cpu: "100m"
                memory: "30Mi"
        #env:
        #- name: 
        #  value: 
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongo-volume        
      restartPolicy: Always
      volumes:
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: mongo-claim