#Pod’s configuration file specifies a PersistentVolumeClaim,
#but it does not specify a PersistentVolume.
#From the Pod’s point of view, the claim is a volume.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  labels:
    k8s-app: mlflow
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      k8s-app: mlflow
  template:
    metadata:
      labels:
        k8s-app: mlflow
    spec:
      nodeName: raspberrypitest
      containers:
      - image: rio05docker/continuos_learning_ui:latest
        imagePullPolicy: Always
        name: mlflow
        resources:
            limits:
                memory: "1Gi"
                cpu: "1"
            requests:
                cpu: "100m"
                memory: "30Mi"
        env:
          - name: LANG
            value: C.UTF-8
          - name: LC_ALL
            value: C.UTF-8
          - name: MLFLOW_S3_ENDPOINT_URL
            value: http://192.168.1.9:32590
          - name: AWS_ACCESS_KEY_ID
            value: minio
          - name: AWS_SECRET_ACCESS_KEY
            value: minio123
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /tmp/mlflowruns
          name: mlflow-volume        
      restartPolicy: Always
      volumes:
      - name: mlflow-volume
        persistentVolumeClaim:
          claimName: mlflow-claim